version: 2.1

parameters:
  run-build:
    type: boolean
    default: false
  region:
    type: string
    default: "na"

commands:
  print:
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.region >>
      
jobs:
  build:
    machine: true
    steps:
      - run: "Dummy build"
      - run: echo << parameters.region >>
      
  cat-file:
    parameters:
      file:
        type: string
    steps:
      - print:
          message: Printing << parameters.file >>
      - run: cat << parameters.file >>

workflows:
  version: 2.1
  infrastructure:
    when: << pipeline.parameters.run-build >>
    jobs:
      - build
      
  my-workflow:
    when: << pipeline.parameters.run-region >>
    jobs:
      - build

