version: 2.1

parameters:
  region:
    type: string
    default: "na"

      
jobs:
  build:
    parameters:
      region:
        type: string
        default: "na"
    machine: true
    steps:
      - run: echo << parameters.region >>
      
workflows:
  version: 2.1  
  my-workflow:
    jobs:
      - build
        matrix:
          parameters:
            region: [
               "eu1", 
               "ap1"
            ]

