version: 2.1

parameters:
  run-region:
    type: boolean
    default: false
  region:
    type: string
    default: "na"

      
jobs:
  build:
    machine: true
    steps:
      - run: echo << pipeline.parameters.region >>
      
workflows:
  version: 2.1  
  my-workflow:
    when: << pipeline.parameters.run-region >>
    jobs:
      - build

