version: 2.1

parameters:
  region-ap1:
    type: boolean
    default: false
  region-eu1:
    type: boolean
    default: false

aliases:
  - &region-specific
    filters:
      branches:
        ignore: /<< matrix.region >>.*/
    matrix:
      parameters:
        region: [
           <<#pipeline.parameters.region-eu1>>eu1<</pipeline.parameters.region-eu1>>,
           <<#pipeline.parameters.region-ap1>>ap1<</pipeline.parameters.region-ap1>>,
        ]

jobs:
  build:
    parameters:
      region:
        type: string
        default: "na"
    machine: true
    steps:
      - run: echo << parameters.region >>
      
workflows:
  version: 2.1  
  my-workflow:
    jobs:
      - build:
          <<: *region-specific

