version: 2.1

parameters:
  run-build:
    type: boolean
    default: false
  region:
    type: string
    default: "na"

      
jobs:
  build:
    machine: true
    steps:
      - run: "Dummy build"
      - run: echo << pipeline.parameters.region >>
      
workflows:
  version: 2.1
  infrastructure:
    when: << pipeline.parameters.run-build >>
    jobs:
      - build
      
  my-workflow:
    jobs:
      - build

